# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hook_out": "00_core.ipynb",
         "KL": "00_core.ipynb",
         "adv_project": "00_core.ipynb",
         "compute_adversarial_loss": "00_core.ipynb",
         "ALUMCallback": "00_core.ipynb",
         "VATCallback": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://aikindergarten.github.io/vat/"

git_url = "https://github.com/aikindergarten/vat/tree/master/"

def custom_doc_links(name): return None
