# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mb_item": "00_core.ipynb",
         "LossCallback": "00_core.ipynb",
         "hook_out": "00_core.ipynb",
         "KL": "00_core.ipynb",
         "SymmetrizedKL": "00_core.ipynb",
         "adv_project": "00_core.ipynb",
         "compute_adversarial_loss": "00_core.ipynb",
         "ALUMCallback": "00_core.ipynb",
         "update_ema_model": "00_core.ipynb",
         "SMARTCallback": "00_core.ipynb",
         "VATCallback": "00_core.ipynb",
         "train_only_metrics": "01_utils.ipynb",
         "Recorder.add_train_metrics": "01_utils.ipynb",
         "WandbCallback": "01_utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "https://aikindergarten.github.io/vat/"

git_url = "https://github.com/aikindergarten/vat/tree/master/"

def custom_doc_links(name): return None
