# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['ALUMCallback', 'VATCallback']

# Cell
from fastai.basics import *
from fastai.test_utils import synth_learner

# Cell
class ALUMCallback(Callback):
    "ALUM callback (draft)"
    run_valid=False

    def __init__(self, m, start_iter=None): #?? potentially start in the middle of training
        self.m = m

    def after_loss(self):
        #TODO: detach as appropriate
        old_weight = self.m.weight.data
        logits = self.pred
        print(f'{self.train_iter:2} - Do stuff here with weights of shape {old_weight.shape} and logits {logits.shape} and modify loss {self.loss:.4f}')
        # do ALUM stuff here


# Cell
class VATCallback(Callback):
    "VAT callback (draft)"
    run_valid=False
    # mb worth adding capability to inject adversarial noize into intermediate activations
    # for ALUM case we could perturb outputs of the embedding layer instead of embedding weights (which would be equivalent)
    def __init__(self, start_iter=None): #?? potentially start in the middle of training

        self.start_iter = start_iter

    def after_loss(self):
        #TODO: detach as appropriate
        noize = 0
        x_adv = self.x + noize #?? take care of possible multiple inputs
        logits = self.pred
        print(f'{self.train_iter:2} - Do stuff here with input of shape {self.x.shape} and logits {logits.shape} and modify loss {self.loss:.4f}')
        # do VAT stuff here
