# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['ALUMCallback']

# Cell
from fastai.basics import *
from fastai.test_utils import synth_learner

# Cell
class ALUMCallback(Callback):
    "ALUM callback (draft)"
    run_valid=False

    def __init__(self, m, start_iter=None): #?? potentially start in the middle of training
        self.m = m

    def after_loss(self):
        #TODO: detach as appropriate
        old_weight = self.m.weight.data
        logits = self.pred
        print(f'{self.train_iter:2} - Do stuff here with weights of shape {old_weight.shape} and logits {logits.shape} and modify loss {self.loss:.4f}')
        # do ALUM stuff here
